#theme: jekyll-theme-minimal
remote_theme: sermonindex/simple-dark@master
title: Computational social science final project; Musician community analysis in Denmark
description: This project is about analysing the local musician communities in Denmark.
